FROM node:18.7.0-alpine

RUN apk update && apk add python3 make g++

RUN mkdir -p /home/node/aspnetcore-react-ssr/node_modules && chown -R node:node /home/node/aspnetcore-react-ssr

WORKDIR /home/node/aspnetcore-react-ssr

COPY package.json ./

COPY package-lock.json ./

USER root

RUN npm install

USER node

COPY --chown=node:node . .

EXPOSE 9009

CMD [ "npm", "run", "storybook" ]